11 
    de.renew.gui.CPNDrawing 90 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 548 283 456 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 549 459 420 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 550 405 464 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 551 215 394 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 552 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 212 396 "p_r2" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 553 350 394 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 554 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 346 396 "p_s2" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 555 215 275 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 556 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 211 277 "p_s1" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 557 350 274 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 558 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 347 276 "p_r1" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 559 103 254 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 560 283 212 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 561 58 196 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 562 161 465 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 563 527 470 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 564 459 247 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 565 528 200 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 566 161 204 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 567 102 403 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 568 404 204 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 569 47 477 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 570 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 54 479 "1" "SansSerif" 0 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 571 346 215 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 572 219 215 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 573 346 453 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 574 461 470 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 575 220 453 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 576 460 198 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 577 214 334 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 578 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 210 336 "s1_2" "SansSerif" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 579 106 473 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 580 105 196 20 20 NULL  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 581 351 334 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 582 "LineStyle" "String" "" 2 470 470 469 440 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 2   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 583 "LineStyle" "String" "" 2 225 295 224 334 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 584 "LineStyle" "String" "" 2 424 214 460 209 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 29  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 585 "LineStyle" "String" "" 2 356 453 360 414 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 586 "LineStyle" "String" "" 2 239 224 284 222 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 587 "LineStyle" "String" "" 2 469 218 469 248 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 25   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 588 "LineStyle" "String" "" 2 226 414 229 453 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 4  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 589 "LineStyle" "String" "" 2 181 216 219 223 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 27  
            CH.ifa.draw.standard.ChopBoxConnector REF 35   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 590 "LineStyle" "String" "" 2 125 207 162 214 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.figures.ChopEllipseConnector REF 27   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 591 "LineStyle" "String" "" 2 240 463 284 466 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 38  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 592 "LineStyle" "String" "" 2 303 466 346 463 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 36   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 593 "LineStyle" "String" "" 2 228 235 226 276 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 35  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 594 "LineStyle" "String" "" 2 181 474 220 465 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 23  
            CH.ifa.draw.standard.ChopBoxConnector REF 38   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 595 "LineStyle" "String" "" 2 224 354 225 395 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 40  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 596 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 221 366 "2" "SansSerif" 0 12 0 REF 99 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 597 "LineStyle" "String" "" 2 366 464 406 473 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 36  
            CH.ifa.draw.figures.ChopEllipseConnector REF 3   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 598 "LineStyle" "String" "" 2 303 222 346 224 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 34   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 599 "LineStyle" "String" "" 2 366 223 405 216 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.figures.ChopEllipseConnector REF 29   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 600 "LineStyle" "String" "" 2 67 487 106 483 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 30  
            CH.ifa.draw.standard.ChopBoxConnector REF 44   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 601 "LineStyle" "String" "" 2 360 275 356 235 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 34   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 602 "LineStyle" "String" "" 2 360 395 360 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 603 "LineStyle" "String" "" 2 115 473 113 423 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 604 "LineStyle" "String" "" 2 114 216 113 255 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 45  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 605 "LineStyle" "String" "" 2 481 480 528 480 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 37  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 606 "LineStyle" "String" "" 2 480 208 529 210 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 607 "LineStyle" "String" "" 2 126 481 162 476 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 44  
            CH.ifa.draw.figures.ChopEllipseConnector REF 23   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 608 "LineStyle" "String" "" 2 425 475 461 478 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 3  
            CH.ifa.draw.standard.ChopBoxConnector REF 37   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 609 "LineStyle" "String" "" 2 360 334 360 294 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 610 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 357 306 "1" "SansSerif" 0 12 0 REF 154 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 611 "LineStyle" "String" "" 2 78 206 105 206 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector REF 45   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 612 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 345 318 "s2_1" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator -2 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 613 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 91 391 "test_b2" "SansSerif" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 614 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 106 500 "t_b2" "SansSerif" 1 12 0 REF 44 
            CH.ifa.draw.standard.OffsetLocator 2 25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 615 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 45 501 "p_b2" "SansSerif" 1 12 0 REF 30 
            CH.ifa.draw.standard.OffsetLocator 2 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 616 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 147 485 "intern_b2" "SansSerif" 1 12 0 REF 23 
            CH.ifa.draw.standard.OffsetLocator 3 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 617 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 222 476 "t_r2" "SansSerif" 1 12 0 REF 38 
            CH.ifa.draw.standard.OffsetLocator 3 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 618 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 270 477 "intern_r2" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 3 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 619 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 344 476 "t_s2" "SansSerif" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 0 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 620 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 388 487 "intern_s2" "SansSerif" 1 12 0 REF 3 
            CH.ifa.draw.standard.OffsetLocator 0 21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 621 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 460 496 "t_e2" "SansSerif" 1 12 0 REF 37 
            CH.ifa.draw.standard.OffsetLocator 1 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 622 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 524 489 "p_e2" "SansSerif" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 1 17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 623 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 448 403 "test_e2" "SansSerif" 1 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator 0 -19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 624 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 216 190 "t_s1" "SansSerif" 1 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator -1 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 625 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 265 193 "intern_s1" "SansSerif" 1 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator -1 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 626 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 346 195 "t_r1" "SansSerif" 1 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 1 -22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 627 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 388 185 "intern_r1" "SansSerif" 1 12 0 REF 29 
            CH.ifa.draw.standard.OffsetLocator 0 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 628 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 457 174 "t_e1" "SansSerif" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator -1 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 629 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 524 184 "p_e1" "SansSerif" 1 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 -18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 630 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 448 269 "test_e1" "SansSerif" 1 12 0 REF 25 
            CH.ifa.draw.standard.OffsetLocator 0 20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 631 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 92 272 "test_b1" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 0 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 632 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 101 174 "t_b1" "SansSerif" 1 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -2 -24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 633 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 140 179 "intern_b1" "SansSerif" 1 12 0 REF 27 
            CH.ifa.draw.standard.OffsetLocator -4 -27 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 634 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 65 199 "1" "SansSerif" 0 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 0 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "FigureWithID" "Int" 635 "FrameColor" "Color" 255 199 158 255 "TextAlignment" "Int" 1 "FillColor" "Color" 255 199 158 255 55 172 "p_b1" "SansSerif" 1 12 0 REF 22 
            CH.ifa.draw.standard.OffsetLocator 1 -26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 636 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 0 0 "FORMULA EXPATH EVENTUALLY intern_r2 = 0 AND test_e2 > 0 AND intern_s2 = 0 AND p_r2 = 0 AND p_s2 = 0 AND p_s1 = 0 AND p_r1 = 0 AND test_b1 > 0 AND intern_s1 = 0 AND p_b1 = 0 AND intern_b2 = 0 AND p_e2 > 0 AND test_e1 > 0 AND p_e1 > 0 AND intern_b1 = 0 AND test_b2 > 0 AND intern_r1 = 0 AND p_b2 = 0 " "SansSerif" 0 12 0 NULL NULL  
        CH.ifa.draw.figures.TextFigure "attributes" "attributes" 3 "FigureWithID" "Int" 637 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 0 40 "FORMULA EXPATH EVENTUALLY ( test_b1 = 0 OR test_e1 > 0 ) AND ( test_b2 = 0 OR test_e2 > 0 ) " "SansSerif" 0 12 0 NULL NULL  NULL  0 161 815 845 